import { Fragment, useCallback, useEffect, useState } from 'react';
import { toast } from 'react-toastify';
import { Dialog, DialogButton, DialogDescription, DialogRoot, DialogTitle } from '~/components/ui/Dialog';
import { setThemeMode, themeModeStore } from '~/lib/stores/theme';
import { db, deleteById, getAll, chatId, description, type ChatHistoryItem, useChatHistory } from '~/lib/persistence';
import { deriveChatTitleFromMessages } from '~/lib/persistence/chatTitle';
import { HistoryItem } from './HistoryItem';
import { binDates } from './date-binning';
import { useSearchFilter } from '~/lib/hooks/useSearchFilter';
import { useStore } from '@nanostores/react';
import { profileStore } from '~/lib/stores/profile';
import { ProjectsWorkspacePanel } from './ProjectsWorkspacePanel';
import { ArtifactsMarketplacePanel } from './ArtifactsMarketplacePanel';

interface MenuProps {
  collapsed: boolean;
  onToggle: () => void;
  onOpenSettings: (tab?: 'profile' | 'settings') => void;
}

function getMessageFingerprint(message?: ChatHistoryItem['messages'][number]): string {
  if (!message) {
    return '';
  }

  const content = typeof message.content === 'string' ? message.content : '';
  const parts = Array.isArray(message.parts)
    ? message.parts
        .map((part) => {
          if (part.type === 'text') {
            return part.text ?? '';
          }

          if (part.type === 'file') {
            return part.filename ?? '';
          }

          return '';
        })
        .join(' ')
    : '';

  const normalizedContent = (content || parts).replace(/\s+/g, ' ').trim().toLowerCase();

  return `${message.role}:${normalizedContent.slice(0, 180)}`;
}

function choosePreferredHistoryItem(current: ChatHistoryItem | undefined, candidate: ChatHistoryItem): ChatHistoryItem {
  if (!current) {
    return candidate;
  }

  const currentMessageCount = current.messages?.length || 0;
  const candidateMessageCount = candidate.messages?.length || 0;

  if (candidateMessageCount !== currentMessageCount) {
    return candidateMessageCount > currentMessageCount ? candidate : current;
  }

  const currentTime = Date.parse(current.timestamp || '');
  const candidateTime = Date.parse(candidate.timestamp || '');
  const hasValidCandidateTime = Number.isFinite(candidateTime);
  const hasValidCurrentTime = Number.isFinite(currentTime);

  if (hasValidCandidateTime && (!hasValidCurrentTime || candidateTime > currentTime)) {
    return candidate;
  }

  return current;
}

function getHistoryFingerprints(item: ChatHistoryItem): string[] {
  return (item.messages || []).map((message) => getMessageFingerprint(message)).filter(Boolean);
}

function getFirstFingerprintByRole(item: ChatHistoryItem, role: 'user' | 'assistant'): string {
  for (const message of item.messages || []) {
    if (message.role === role) {
      const fingerprint = getMessageFingerprint(message);

      if (fingerprint) {
        return fingerprint;
      }
    }
  }

  return '';
}

function isLikelyAutoGeneratedDiscussionLabel(description: string): boolean {
  const normalized = description.trim().toLowerCase();

  return normalized.startsWith('[model:') || normalized === 'new chat' || normalized.startsWith('discussion ');
}

function isSuffixMatch(longer: string[], shorter: string[]): boolean {
  if (shorter.length === 0 || shorter.length > longer.length) {
    return false;
  }

  const offset = longer.length - shorter.length;

  return shorter.every((fingerprint, index) => longer[offset + index] === fingerprint);
}

function shouldCollapseHistoryItems(left: ChatHistoryItem, right: ChatHistoryItem): boolean {
  const leftDescription = (left.description || '').trim().toLowerCase();
  const rightDescription = (right.description || '').trim().toLowerCase();
  const leftAutoGenerated = isLikelyAutoGeneratedDiscussionLabel(leftDescription);
  const rightAutoGenerated = isLikelyAutoGeneratedDiscussionLabel(rightDescription);

  if (!leftDescription || !rightDescription) {
    return false;
  }

  if (leftDescription !== rightDescription && !(leftAutoGenerated && rightAutoGenerated)) {
    return false;
  }

  const leftFingerprints = getHistoryFingerprints(left);
  const rightFingerprints = getHistoryFingerprints(right);

  if (leftFingerprints.length === 0 || rightFingerprints.length === 0) {
    return leftAutoGenerated && rightAutoGenerated;
  }

  if (leftFingerprints.length >= rightFingerprints.length) {
    if (isSuffixMatch(leftFingerprints, rightFingerprints)) {
      return true;
    }
  } else if (isSuffixMatch(rightFingerprints, leftFingerprints)) {
    return true;
  }

  if (leftAutoGenerated && rightAutoGenerated) {
    const leftFirstUser = getFirstFingerprintByRole(left, 'user');
    const rightFirstUser = getFirstFingerprintByRole(right, 'user');

    if (leftFirstUser && rightFirstUser && leftFirstUser === rightFirstUser) {
      return true;
    }
  }

  return false;
}

function buildDistinctDiscussionName(baseName: string, index: number): string {
  return `${String(index + 1).padStart(3, '0')}- ${baseName}`;
}

export function ensureDistinctChatNames(items: ChatHistoryItem[]): ChatHistoryItem[] {
  const groupedByName = new Map<string, ChatHistoryItem[]>();

  for (const item of items) {
    const normalizedName = (item.description || '').trim().toLowerCase();

    if (!normalizedName) {
      continue;
    }

    const group = groupedByName.get(normalizedName) || [];
    group.push(item);
    groupedByName.set(normalizedName, group);
  }

  const itemsById = new Map(items.map((item) => [item.id, item]));

  for (const [_, duplicates] of groupedByName) {
    if (duplicates.length < 2) {
      continue;
    }

    const orderedDuplicates = [...duplicates].sort((left, right) => {
      const leftTime = Date.parse(left.timestamp || '');
      const rightTime = Date.parse(right.timestamp || '');

      if (Number.isFinite(leftTime) && Number.isFinite(rightTime)) {
        return leftTime - rightTime;
      }

      if (Number.isFinite(leftTime)) {
        return -1;
      }

      if (Number.isFinite(rightTime)) {
        return 1;
      }

      return left.id.localeCompare(right.id);
    });

    const baseName = (orderedDuplicates[0].description || '').trim();

    orderedDuplicates.forEach((item, index) => {
      itemsById.set(item.id, {
        ...item,
        description: buildDistinctDiscussionName(baseName, index),
      });
    });
  }

  return items.map((item) => itemsById.get(item.id) || item);
}

export function dedupeAccidentalHistoryCopies(items: ChatHistoryItem[]): ChatHistoryItem[] {
  const byIdentity = new Map<string, ChatHistoryItem>();

  for (const item of items) {
    const identityKey = (item.urlId || item.id || '').trim().toLowerCase();

    if (identityKey) {
      byIdentity.set(identityKey, choosePreferredHistoryItem(byIdentity.get(identityKey), item));
      continue;
    }

    byIdentity.set(`fallback:${byIdentity.size}`, item);
  }

  const deduped: ChatHistoryItem[] = [];

  for (const item of byIdentity.values()) {
    const duplicateIndex = deduped.findIndex((existing) => shouldCollapseHistoryItems(existing, item));

    if (duplicateIndex >= 0) {
      deduped[duplicateIndex] = choosePreferredHistoryItem(deduped[duplicateIndex], item);
    } else {
      deduped.push(item);
    }
  }

  return deduped.sort((left, right) => {
    const rightTime = Date.parse(right.timestamp || '');
    const leftTime = Date.parse(left.timestamp || '');

    if (Number.isFinite(rightTime) && Number.isFinite(leftTime)) {
      return rightTime - leftTime;
    }

    if (Number.isFinite(rightTime)) {
      return 1;
    }

    if (Number.isFinite(leftTime)) {
      return -1;
    }

    return 0;
  });
}

export function normalizeHistoryItemsForSidebar(items: ChatHistoryItem[]): ChatHistoryItem[] {
  return items
    .filter((item) => item.urlId)
    .map((item) => {
      const normalizedDescription = item.description?.trim();
      const derivedDescription = deriveChatTitleFromMessages(item.messages || [], item.urlId || 'Untitled chat')?.trim();

      return {
        ...item,
        description: normalizedDescription || derivedDescription || item.urlId || 'Untitled chat',
      };
    });
}

function getInitials(name?: string): string {
  if (!name) return 'U';
  const parts = name.trim().split(/\s+/);
  if (parts.length >= 2) return (parts[0][0] + parts[1][0]).toUpperCase();
  return parts[0][0].toUpperCase();
}

export const Menu = ({ collapsed, onToggle, onOpenSettings }: MenuProps) => {
  const { exportChat, duplicateCurrentChat } = useChatHistory();
  const [list, setList] = useState<ChatHistoryItem[]>([]);
  const [dialogContent, setDialogContent] = useState<{ type: 'delete'; item: ChatHistoryItem } | null>(null);
  const [activeSection, setActiveSection] = useState<'chats' | 'projects' | 'artifacts' | 'code'>('chats');
  const [loggingOut, setLoggingOut] = useState(false);
  const profile = useStore(profileStore);
  const themeMode = useStore(themeModeStore);
  const activeChatId = useStore(chatId);
  const currentDescription = useStore(description);

  const { filteredItems: filteredList, handleSearchChange } = useSearchFilter({
    items: list,
    searchFields: ['description'],
  });

  const loadEntries = useCallback(() => {
    if (db) {
      getAll(db)
        .then((items) => normalizeHistoryItemsForSidebar(items))
        .then((items) => dedupeAccidentalHistoryCopies(items))
        .then((items) => ensureDistinctChatNames(items))
        .then(setList)
        .catch((error) => toast.error(error.message));
    }
  }, []);

  const deleteItem = useCallback(
    async (event: React.UIEvent, item: ChatHistoryItem) => {
      event.preventDefault();

      if (!db) return;

      try {
        const allItems = await getAll(db);
        const normalizedItems = normalizeHistoryItemsForSidebar(allItems);
        const targetIds = new Set<string>();

        for (const candidate of normalizedItems) {
          if (candidate.id === item.id || candidate.urlId === item.urlId || shouldCollapseHistoryItems(candidate, item)) {
            targetIds.add(candidate.id);
          }
        }

        if (targetIds.size === 0) {
          targetIds.add(item.id);
        }

        await Promise.all([...targetIds].map((id) => deleteById(db, id)));

        toast.success('Chat deleted');
        loadEntries();

        const isActivePath = typeof window !== 'undefined' && item.urlId
          ? window.location.pathname === `/chat/${item.urlId}`
          : false;

        if (chatId.get() === item.id || isActivePath) {
          window.location.pathname = '/';
        }
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : 'Failed to delete chat';
        toast.error(message);
      }
    },
    [loadEntries],
  );

  useEffect(() => {
    loadEntries();
  }, [loadEntries, activeChatId, currentDescription]);

  useEffect(() => {
    const refreshIfVisible = () => {
      if (typeof document === 'undefined' || document.visibilityState === 'visible') {
        loadEntries();
      }
    };

    window.addEventListener('focus', refreshIfVisible);
    window.addEventListener('pageshow', refreshIfVisible);
    document.addEventListener('visibilitychange', refreshIfVisible);

    return () => {
      window.removeEventListener('focus', refreshIfVisible);
      window.removeEventListener('pageshow', refreshIfVisible);
      document.removeEventListener('visibilitychange', refreshIfVisible);
    };
  }, [loadEntries]);

  const handleLogout = useCallback(async () => {
    if (loggingOut) {
      return;
    }

    setLoggingOut(true);

    try {
      const response = await fetch('/api/auth/logout', {
        method: 'POST',
      });

      if (!response.ok) {
        throw new Error('Logout failed');
      }

      window.location.href = '/';
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Logout failed');
      setLoggingOut(false);
    }
  }, [loggingOut]);

  // Ordered: Projects / Artifacts / Code — gap — Chats
  const navItems: Array<{
    key: 'projects' | 'artifacts' | 'code' | 'chats';
    label: string;
    icon: string;
    separator?: boolean;
  }> = [
    { key: 'projects', label: 'Projects', icon: '📁' },
    { key: 'artifacts', label: 'Artifacts', icon: '📦' },
    { key: 'code', label: 'Code', icon: '{ }' },
    { key: 'chats', label: 'Chats', icon: '💬', separator: true },
  ];
  return (
    <>
      <div
        style={{
          gridRow: '1 / span 2',
          background: 'var(--bolt-elements-sidebar-background)',
          borderRight: '1px solid var(--bolt-elements-borderColor)',
          display: 'flex',
          flexDirection: 'column',
          height: '100%',
          overflow: 'hidden',
          fontSize: '14px',
          color: 'var(--bolt-elements-textPrimary)',
        }}
      >
        {/* Logo + toggle */}
        <div
          style={{
            display: 'flex',
            flexDirection: collapsed ? 'column' : 'row',
            justifyContent: collapsed ? 'flex-start' : 'space-between',
            alignItems: 'center',
            padding: collapsed ? '10px 6px' : '14px',
            fontWeight: 600,
            borderBottom: '1px solid var(--bolt-elements-borderColor)',
            minHeight: '60px',
            gap: collapsed ? '6px' : '8px',
          }}
        >
          {!collapsed && (
            <img
              src="/logo-opurion-full.png"
              alt="Opurion"
              style={{ height: '30px', width: 'auto', objectFit: 'contain', flex: 1, minWidth: 0 }}
            />
          )}
          {collapsed && (
            <img
              src="/logo-opurion-mark.png"
              alt="Opurion"
              style={{ width: '36px', height: '36px', objectFit: 'contain', flexShrink: 0 }}
            />
          )}
          <button
            onClick={onToggle}
            style={{
              background: 'none',
              border: 'none',
              color: 'var(--bolt-elements-textPrimary)',
              cursor: 'pointer',
              fontSize: '18px',
              lineHeight: 1,
              padding: '2px 4px',
              borderRadius: '4px',
              flexShrink: 0,
            }}
            aria-label="Toggle sidebar"
          >
            ☰
          </button>
        </div>

        {/* Nav */}
        <nav
          style={{
            padding: '8px',
            display: 'flex',
            flexDirection: 'column',
            gap: '2px',
            flex: 1,
            overflow: 'hidden',
          }}
        >
          {/* New chat */}
          <a
            href="/"
            style={{
              display: 'block',
              padding: '8px 10px',
              borderRadius: '6px',
              textDecoration: 'none',
              color: 'var(--bolt-elements-textPrimary)',
              background: 'rgba(120,120,120,.12)',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              textAlign: collapsed ? 'center' : 'left',
            }}
            title="New chat"
          >
            {collapsed ? '✏' : 'New chat'}
          </a>

          {/* Section nav items */}
          {navItems.map(({ key, label, icon, separator }) => (
            <Fragment key={key}>
              {separator && (
                <div
                  style={{ height: '1px', background: 'var(--bolt-elements-borderColor, #2b2b33)', margin: '4px 0' }}
                />
              )}
              <button
                onClick={() => {
                  if (collapsed) onToggle();
                  setActiveSection(key);
                }}
                style={{
                  display: 'block',
                  width: '100%',
                  textAlign: collapsed ? 'center' : 'left',
                  padding: '8px 10px',
                  borderRadius: '6px',
                  border: 'none',
                  background: 'transparent',
                  color: 'var(--bolt-elements-textPrimary)',
                  fontSize: '14px',
                  fontWeight: activeSection === key ? 700 : 400,
                  cursor: 'pointer',
                  whiteSpace: 'nowrap',
                  overflow: 'hidden',
                }}
                title={label}
              >
                {collapsed ? icon : label}
              </button>
            </Fragment>
          ))}

          {/* Chat history list (only when expanded and Chats active) */}
          {!collapsed && activeSection === 'chats' && (
            <div
              style={{
                marginTop: '8px',
                flex: 1,
                overflow: 'hidden',
                display: 'flex',
                flexDirection: 'column',
                minHeight: 0,
              }}
            >
              <input
                type="search"
                placeholder="Search chats…"
                onChange={handleSearchChange}
                style={{
                  width: '100%',
                  padding: '6px 10px',
                  borderRadius: '6px',
                  border: '1px solid var(--bolt-elements-borderColor)',
                  background: 'var(--bolt-elements-background-depth-2)',
                  color: 'var(--bolt-elements-textPrimary)',
                  fontSize: '13px',
                  marginBottom: '6px',
                  boxSizing: 'border-box',
                  outline: 'none',
                }}
              />
              <div style={{ flex: 1, overflowY: 'auto', fontSize: '13px' }}>
                {filteredList.length === 0 && (
                  <div style={{ padding: '6px 10px', color: 'var(--bolt-elements-textTertiary)' }}>
                    No conversations
                  </div>
                )}
                <DialogRoot open={dialogContent !== null}>
                  {binDates(filteredList).map(({ category, items }) => (
                    <div key={category}>
                      <div
                        style={{
                          padding: '4px 10px',
                          color: 'var(--bolt-elements-textTertiary)',
                          fontSize: '11px',
                          textTransform: 'uppercase',
                          letterSpacing: '.05em',
                        }}
                      >
                        {category}
                      </div>
                      {items.map((item) => (
                        <HistoryItem
                          key={item.id}
                          item={item}
                          exportChat={exportChat}
                          onDelete={(e) => {
                            e.preventDefault();
                            setDialogContent({ type: 'delete', item });
                          }}
                          onDuplicate={duplicateCurrentChat}
                          selectionMode={false}
                          isSelected={false}
                          onToggleSelection={() => {}}
                        />
                      ))}
                    </div>
                  ))}
                  <Dialog onBackdrop={() => setDialogContent(null)} onClose={() => setDialogContent(null)}>
                    {dialogContent?.type === 'delete' && (
                      <>
                        <div className="p-6 bg-bolt-elements-background-depth-1">
                          <DialogTitle className="text-bolt-elements-textPrimary">Delete Chat?</DialogTitle>
                          <DialogDescription className="mt-2 text-bolt-elements-textSecondary">
                            Delete &quot;{dialogContent.item.description}&quot;?
                          </DialogDescription>
                        </div>
                        <div className="flex justify-end gap-3 px-6 py-4 bg-bolt-elements-background-depth-2 border-t border-bolt-elements-borderColor">
                          <DialogButton type="secondary" onClick={() => setDialogContent(null)}>
                            Cancel
                          </DialogButton>
                          <DialogButton
                            type="danger"
                            onClick={(e) => {
                              deleteItem(e, dialogContent.item);
                              setDialogContent(null);
                            }}
                          >
                            Delete
                          </DialogButton>
                        </div>
                      </>
                    )}
                  </Dialog>
                </DialogRoot>
              </div>
            </div>
          )}

          {/* Project / Artifact / Code stub panels */}
          {!collapsed && activeSection !== 'chats' && (
            <div style={{ marginTop: '8px', overflowY: 'auto', maxHeight: '100%' }}>
              {activeSection === 'projects' && <ProjectsWorkspacePanel />}
              {activeSection === 'artifacts' && <ArtifactsMarketplacePanel />}
              {activeSection === 'code' && (
                <div
                  style={{
                    padding: '10px',
                    borderRadius: '8px',
                    border: '1px solid var(--bolt-elements-borderColor)',
                    background: 'var(--bolt-elements-background-depth-2)',
                    color: 'var(--bolt-elements-textTertiary)',
                    fontSize: '13px',
                  }}
                >
                  Code section will show project code context and shared assets here.
                </div>
              )}
            </div>
          )}
        </nav>

        {/* Footer: theme + settings + profile */}
        <div
          style={{
            padding: '12px',
            borderTop: '1px solid var(--bolt-elements-borderColor)',
            display: 'flex',
            flexDirection: 'column',
            alignItems: collapsed ? 'center' : 'stretch',
            gap: '8px',
          }}
        >
          {/* Theme slider — horizontal when expanded, vertical when collapsed */}
          {!collapsed ? (
            <div
              style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
              title={themeMode === 'dark' ? 'Switch to light' : 'Switch to dark'}
            >
              <span style={{ fontSize: '13px' }}>☀️</span>
              <label style={{ position: 'relative', width: '36px', height: '20px', cursor: 'pointer', flexShrink: 0 }}>
                <input
                  type="checkbox"
                  checked={themeMode === 'dark'}
                  onChange={() => setThemeMode(themeMode === 'dark' ? 'light' : 'dark')}
                  style={{ display: 'none' }}
                />
                <span
                  style={{
                    position: 'absolute',
                    inset: 0,
                    background: themeMode === 'dark' ? '#5a5a7a' : '#888',
                    borderRadius: '20px',
                    transition: '.2s',
                  }}
                />
                <span
                  style={{
                    position: 'absolute',
                    top: '2px',
                    left: themeMode === 'dark' ? '18px' : '2px',
                    width: '16px',
                    height: '16px',
                    background: 'white',
                    borderRadius: '50%',
                    transition: '.2s',
                  }}
                />
              </label>
              <span style={{ fontSize: '13px' }}>🌙</span>
            </div>
          ) : (
            // Vertical slider when collapsed
            <div
              style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '4px' }}
              title={themeMode === 'dark' ? 'Switch to light' : 'Switch to dark'}
            >
              <span style={{ fontSize: '11px' }}>☀️</span>
              <label style={{ position: 'relative', width: '20px', height: '36px', cursor: 'pointer' }}>
                <input
                  type="checkbox"
                  checked={themeMode === 'dark'}
                  onChange={() => setThemeMode(themeMode === 'dark' ? 'light' : 'dark')}
                  style={{ display: 'none' }}
                />
                <span
                  style={{
                    position: 'absolute',
                    inset: 0,
                    background: themeMode === 'dark' ? '#5a5a7a' : '#888',
                    borderRadius: '20px',
                    transition: '.2s',
                  }}
                />
                <span
                  style={{
                    position: 'absolute',
                    left: '2px',
                    top: themeMode === 'dark' ? '18px' : '2px',
                    width: '16px',
                    height: '16px',
                    background: 'white',
                    borderRadius: '50%',
                    transition: '.2s',
                  }}
                />
              </label>
              <span style={{ fontSize: '11px' }}>🌙</span>
            </div>
          )}

          {/* Settings */}
          <button
            onClick={() => onOpenSettings('settings')}
            title="Settings"
            style={{
              background: 'none',
              border: 'none',
              cursor: 'pointer',
              color: 'var(--bolt-elements-textPrimary)',
              textAlign: collapsed ? 'center' : 'left',
              padding: '4px 0',
              fontSize: '13px',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              width: '100%',
            }}
          >
            {collapsed ? '⚙' : '⚙ Settings'}
          </button>

          <button
            onClick={() => void handleLogout()}
            title="Log out"
            disabled={loggingOut}
            style={{
              background: 'var(--bolt-elements-background-depth-2)',
              border: '1px solid var(--bolt-elements-borderColor)',
              borderRadius: '8px',
              cursor: loggingOut ? 'default' : 'pointer',
              color: 'var(--bolt-elements-textPrimary)',
              textAlign: collapsed ? 'center' : 'left',
              padding: collapsed ? '6px 0' : '6px 10px',
              fontSize: '13px',
              whiteSpace: 'nowrap',
              overflow: 'hidden',
              width: '100%',
              opacity: loggingOut ? 0.6 : 1,
              display: 'flex',
              alignItems: 'center',
              justifyContent: collapsed ? 'center' : 'flex-start',
              gap: collapsed ? '0' : '8px',
            }}
          >
            <span className="i-ph:sign-out text-[14px]" aria-hidden="true" />
            {!collapsed && (loggingOut ? 'Logging out…' : 'Log out')}
          </button>

          {/* Profile */}
          {!collapsed && (
            <button
              onClick={() => onOpenSettings('profile')}
              title="Go to profile settings"
              style={{
                color: 'var(--bolt-elements-textSecondary)',
                fontSize: '13px',
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                width: '100%',
                textAlign: 'left',
                padding: '0',
                fontWeight: 500,
              }}
            >
              {profile?.name || profile?.username || 'user'}
            </button>
          )}

          {collapsed && (
            <button
              onClick={() => onOpenSettings('profile')}
              title={`${profile?.name || profile?.username || 'User'} - Go to profile settings`}
              style={{
                width: '28px',
                height: '28px',
                borderRadius: '50%',
                background: 'rgba(120,120,120,.3)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                fontSize: '11px',
                fontWeight: 600,
                color: 'var(--bolt-elements-textPrimary)',
                marginTop: '2px',
                border: 'none',
                cursor: 'pointer',
                padding: 0,
              }}
            >
              {getInitials(profile?.name || profile?.username)}
            </button>
          )}
        </div>
      </div>
    </>
  );
};
